
#ifndef __APP_H_
#define __APP_H_

#ifdef _APP_C_
#define PUBLIC 
#else
#define PUBLIC  extern
#endif

//total event: 32
#define APP_KEY_CHANGE_EVENT	((uint32_t)(1 << 0))	// 
#define APP_LED_BREATHE_EVENT	((uint32_t)(1 << 1))	// 
#define APP_EVENT_INFO_2		((uint32_t)(1 << 2))	// 
#define APP_EVENT_INFO_3		((uint32_t)(1 << 3))	// 
#define APP_EVENT_INFO_4		((uint32_t)(1 << 4))	// 
#define APP_EVENT_INFO_5		((uint32_t)(1 << 5))	// 
#define APP_EVENT_INFO_6		((uint32_t)(1 << 6))	// 	
#define APP_EVENT_INFO_7		((uint32_t)(1 << 7))	//
#define APP_EVENT_INFO_8		((uint32_t)(1 << 8))	//
#define APP_EVENT_INFO_9		((uint32_t)(1 << 9))	// 
#define APP_EVENT_INFO_10		((uint32_t)(1 << 10))	// 	
#define APP_EVENT_INFO_11		((uint32_t)(1 << 11))	//
#define APP_EVENT_INFO_12		((uint32_t)(1 << 12))	//
#define APP_EVENT_INFO_13		((uint32_t)(1 << 13))	// 
#define APP_EVENT_INFO_14		((uint32_t)(1 << 14))	// 	
#define APP_EVENT_INFO_15		((uint32_t)(1 << 15))	//

enum _APP_STATE{
/* 0*/APP_INIT_STATE = 0,
/* 1*/APP_IDLE_STATE,
/* 2*/APP_STARTUP_STATE,
/* 3*/APP_NORMAL_STATE,
/* 4*/APP_ESPRESSO_STATE,
/* 5*/APP_AMERICAN_STATE,
/* 6*/APP_HOTWATER_STATE,
/* 7*/APP_STEAM_STATE,
/* 8*/APP_AQUA_STATE,
/* 9*/APP_CALC_STATE,
/*10*/APP_SETUP_STATE,

/************ 新增 ***********/
/*11*/APP_RUNNING_ONOFF_STATE,
};

enum _INIT_STATE{
	INIT_STATE = 0,
	INIT_READY_STATE,
	INIT_END_STATE,
};

enum _IDLE_STATE{
	IDLE_INIT_STATE = 0,
	IDLE_RUN_STATE,
	IDLE_KEY_STATE,
};

enum _STARTUP_STATE{
	STARTUP_INIT_STATE = 0,
	STARTUP_ENTRY_STATE,
	STARTUP_RIGHT_RST_STATE,
	STARTUP_LEFT_STATE,
	STARTUP_LEFT_RST_STATE,
	STARTUP_HEAT_RDY_STATE,
	STARTUP_HEAT_ING_STATE,
	STARTUP_HEAT_END_STATE,
	STARTUP_LEFT_MOVE_STATE,
	STARTUP_WATER_RDY_STATE,
	STARTUP_WATER_ING_STATE,
	STARTUP_WATER_END_STATE,
	STARTUP_RIGHT_MOVE_STATE,
	STARTUP_LEFT_START_STATE,
	STARTUP_LEFT_END_STATE,
	STARTUP_COMPLETE_STATE,
	STARTUP_FAIL_STATE,
};

enum _NORMAL_STATE{
	NORMAL_INIT_STATE = 0,
	NORMAL_ESPRESSO_INIT_STATE,
	NORMAL_ESPRESSO_RUN_STATE,
	NORMAL_AMERICANO_INIT_STATE,
	NORMAL_AMERICANO_RUN_STATE,
	NORMAL_HOTWATER_INIT_STATE,
	NORMAL_HOTWATER_RUN_STATE,
	NORMAL_STEAM_INIT_STATE,
	NORMAL_STEAM_RUN_STATE,
	NORMAL_AQUA_INIT_STATE,
	NORMAL_AQUA_RUN_STATE,
	NORMAL_CALC_INIT_STATE,
	NORMAL_CALC_RUN_STATE,
};

enum _ESPRESSO_STATE{
	ESPRESSO_INIT_STATE = 0,
	ESPRESSO_MOTO_CHECK_STATE,				//检查电机状态
	ESPRESSO_MOTO_CHECK_JUDGE_STATE,		//检查电机状态判断
	ESPRESSO_MOTO_FIRST_RST_STATE,			//萃取电机第一次复位
	ESPRESSO_MOTO_CHECK_COMPLETE_STATE,		//检查电机状态完成
	ESPRESSO_GRIND_TIME_JUDGE_STATE,		//研磨时间判断
	ESPRESSO_GRIND_STATE,					//研磨状态
	ESPRESSO_MOTO_GO_BREW_STATE,			//萃取电机右转到萃取位置
	ESPRESSO_MOTO_GO_BREW_JUDGE_STATE,		//萃取电机右转到萃取位置判断
	ESPRESSO_PRE_BREW_STATE,				//预冲煮状态
	ESPRESSO_WAIT_BREW_STATE,				//等待冲煮状态
	ESPRESSO_BREW_STATE,					//冲煮状态
	ESPRESSO_BREW_FINISH_STATE,				//冲煮完成状态
	ESPRESSO_GO_DROP_COFFEE_GROUNDS_STATE,	//前往丢咖啡渣
	ESPRESSO_DROP_COFFEE_GROUNDS_STATE,		//丢咖啡渣
	ESPRESSO_BACK_STATE,					//萃取电机返回
	ESPRESSO_INPLACE_JUDGE_STATE,			//萃取电机返回判断
	ESPRESSO_INPLACE_STATE, 				//萃取电机到位
	ESPRESSO_MOTO_SECOND_RST_STATE,			//萃取电机第二次复位
	ESPRESSO_JUDGE_TWO_CUP_STATE,			//判断是否双杯
	ESPRESSO_COMPLETE_STATE,				//萃取电机复位完成
};

enum _AMERICAN_STATE{
	AMERICAN_INIT_STATE = 0,
	AMERICAN_RIGHT_STATE,
	AMERICAN_RIGHT_RST_STATE,
	AMERICAN_LEFT_STATE,
	AMERICAN_LEFT_RST_STATE,
	AMERICAN_GRIND_INIT_STATE,
	AMERICAN_GRIND_RUN_STATE,
	AMERICAN_GRIND_END_STATE,
	AMERICAN_LEFT_MOVE_STATE,
	AMERICAN_PRECOFFEE_RDY_STATE,
	AMERICAN_PRECOFFEE_ING_STATE,
	AMERICAN_PRECOFFEE_END_STATE,
	AMERICAN_COFFEE_RDY_STATE,
	AMERICAN_COFFEE_ING_STATE,
	AMERICAN_COFFEE_END_STATE,
	AMERICAN_RIGHT_SEG1_STATE,
	AMERICAN_RIGHT_PAUSE_STATE,
	AMERICAN_RIGHT_SEG2_STATE,
	AMERICAN_RIGHT_MOVE_STATE,
	AMERICAN_LEFT_START_STATE,
	AMERICAN_LEFT_END_STATE,
	AMERICAN_EXTRACT_RST_STATE,
	AMERICAN_EXTRACT_CHECK_STATE,

};

enum _HOTWATER_STATE{
	HOTWATER_INIT_STATE = 0,
	HOTWATER_RUN_STATE,
	HOTWATER_KEY_STATE,
};

enum _STEAM_STATE{
	STEAM_INIT_STATE = 0,
	STEAM_RUN_STATE,
	STEAM_KEY_STATE,
};

enum _AQUA_STATE{
	AQUA_INIT_STATE = 0,
	AQUA_RUN_STATE,
	AQUA_KEY_STATE,
};

enum _CALC_STATE{
	CALC_INIT_STATE = 0,
	CALC_RUN_STATE,
	CALC_KEY_STATE,
};

enum _SETUP_STATE{
	SETUP_INIT_STATE = 0,
	SETUP_ENTER_STATE,

	SETUP_ENTER_ING_STATE,

	SETUP_RIGHT_READY_STATE,
	SETUP_RIGHT_ING_STATE,
	SETUP_LEFT_READY_STATE,
	SETUP_LEFT_ING_STATE,
	SETUP_COMPLETE_STATE,
};

/************ 新增 ***********/
enum _RUNNING_ONOFF_STATE{
	RUNNING_ONOFF_GRIND_STATE = 0,
	RUNNING_ONOFF_GO_WATER_STATE,
	RUNNING_ONOFF_PRE_BREW_STATE,
	RUNNING_ONOFF_BREW_STATE,
	RUNNING_ONOFF_FLUSH,
};

#ifndef TRUE
#define TRUE				1
#endif
#ifndef FAIL
#define FAIL				0
#endif

typedef struct
{
	uint8_t cup;
	uint8_t coffee;
	uint8_t water;
}st_opDef;

#define HEAT_MAX_TIMER(x)		(15000/x)
#define WATER_MAX_TIMER(x)		(10000/x)
#define COFFEE_MAX_TIMER(x)		(11900/x)
#define PRECOFFEE_MAX_TIMER(x)	(2100/x)

#define RIGHT_TIMER(y,x)		(y/x)
#define LEFT_TIMER(y,x)			(y/x)

/************ 新增 ***********/
#define GRIND_TIMER(y,x)		(y/x)


PUBLIC uint8_t app_id;
PUBLIC uint8_t app_task_step;
PUBLIC uint8_t app_task_substep;

PUBLIC st_opDef manual_setup; 

void init_app_task(uint8_t id);
void app_task_handler(void);
uint32_t app_event_handler( uint8_t task_id, uint32_t events);
uint8_t app_step_state(uint8_t step);

void app_leds_all_fun(uint8_t status);
void app_buzoff_cbfunc(void);
void app_buzzer_on(uint8_t time);

#undef PUBLIC
#endif

